# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/urban/Desktop/documentenshared/universiteit antwerpen/Gevorderde programeren/Space Invaders"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/urban/Desktop/documentenshared/universiteit antwerpen/Gevorderde programeren/Space Invaders"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/urban/Desktop/documentenshared/universiteit antwerpen/Gevorderde programeren/Space Invaders/CMakeFiles" "/home/urban/Desktop/documentenshared/universiteit antwerpen/Gevorderde programeren/Space Invaders/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/urban/Desktop/documentenshared/universiteit antwerpen/Gevorderde programeren/Space Invaders/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SiegeAlienEdition

# Build rule for target.
SiegeAlienEdition: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SiegeAlienEdition
.PHONY : SiegeAlienEdition

# fast build rule for target.
SiegeAlienEdition/fast:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/build
.PHONY : SiegeAlienEdition/fast

src/SiegeAlienEdition.o: src/SiegeAlienEdition.cpp.o
.PHONY : src/SiegeAlienEdition.o

# target to build an object file
src/SiegeAlienEdition.cpp.o:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/SiegeAlienEdition.cpp.o
.PHONY : src/SiegeAlienEdition.cpp.o

src/SiegeAlienEdition.i: src/SiegeAlienEdition.cpp.i
.PHONY : src/SiegeAlienEdition.i

# target to preprocess a source file
src/SiegeAlienEdition.cpp.i:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/SiegeAlienEdition.cpp.i
.PHONY : src/SiegeAlienEdition.cpp.i

src/SiegeAlienEdition.s: src/SiegeAlienEdition.cpp.s
.PHONY : src/SiegeAlienEdition.s

# target to generate assembly for a file
src/SiegeAlienEdition.cpp.s:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/SiegeAlienEdition.cpp.s
.PHONY : src/SiegeAlienEdition.cpp.s

src/TinyXML/tinystr.o: src/TinyXML/tinystr.cpp.o
.PHONY : src/TinyXML/tinystr.o

# target to build an object file
src/TinyXML/tinystr.cpp.o:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/TinyXML/tinystr.cpp.o
.PHONY : src/TinyXML/tinystr.cpp.o

src/TinyXML/tinystr.i: src/TinyXML/tinystr.cpp.i
.PHONY : src/TinyXML/tinystr.i

# target to preprocess a source file
src/TinyXML/tinystr.cpp.i:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/TinyXML/tinystr.cpp.i
.PHONY : src/TinyXML/tinystr.cpp.i

src/TinyXML/tinystr.s: src/TinyXML/tinystr.cpp.s
.PHONY : src/TinyXML/tinystr.s

# target to generate assembly for a file
src/TinyXML/tinystr.cpp.s:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/TinyXML/tinystr.cpp.s
.PHONY : src/TinyXML/tinystr.cpp.s

src/TinyXML/tinyxml.o: src/TinyXML/tinyxml.cpp.o
.PHONY : src/TinyXML/tinyxml.o

# target to build an object file
src/TinyXML/tinyxml.cpp.o:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/TinyXML/tinyxml.cpp.o
.PHONY : src/TinyXML/tinyxml.cpp.o

src/TinyXML/tinyxml.i: src/TinyXML/tinyxml.cpp.i
.PHONY : src/TinyXML/tinyxml.i

# target to preprocess a source file
src/TinyXML/tinyxml.cpp.i:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/TinyXML/tinyxml.cpp.i
.PHONY : src/TinyXML/tinyxml.cpp.i

src/TinyXML/tinyxml.s: src/TinyXML/tinyxml.cpp.s
.PHONY : src/TinyXML/tinyxml.s

# target to generate assembly for a file
src/TinyXML/tinyxml.cpp.s:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/TinyXML/tinyxml.cpp.s
.PHONY : src/TinyXML/tinyxml.cpp.s

src/TinyXML/tinyxmlerror.o: src/TinyXML/tinyxmlerror.cpp.o
.PHONY : src/TinyXML/tinyxmlerror.o

# target to build an object file
src/TinyXML/tinyxmlerror.cpp.o:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/TinyXML/tinyxmlerror.cpp.o
.PHONY : src/TinyXML/tinyxmlerror.cpp.o

src/TinyXML/tinyxmlerror.i: src/TinyXML/tinyxmlerror.cpp.i
.PHONY : src/TinyXML/tinyxmlerror.i

# target to preprocess a source file
src/TinyXML/tinyxmlerror.cpp.i:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/TinyXML/tinyxmlerror.cpp.i
.PHONY : src/TinyXML/tinyxmlerror.cpp.i

src/TinyXML/tinyxmlerror.s: src/TinyXML/tinyxmlerror.cpp.s
.PHONY : src/TinyXML/tinyxmlerror.s

# target to generate assembly for a file
src/TinyXML/tinyxmlerror.cpp.s:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/TinyXML/tinyxmlerror.cpp.s
.PHONY : src/TinyXML/tinyxmlerror.cpp.s

src/TinyXML/tinyxmlparser.o: src/TinyXML/tinyxmlparser.cpp.o
.PHONY : src/TinyXML/tinyxmlparser.o

# target to build an object file
src/TinyXML/tinyxmlparser.cpp.o:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/TinyXML/tinyxmlparser.cpp.o
.PHONY : src/TinyXML/tinyxmlparser.cpp.o

src/TinyXML/tinyxmlparser.i: src/TinyXML/tinyxmlparser.cpp.i
.PHONY : src/TinyXML/tinyxmlparser.i

# target to preprocess a source file
src/TinyXML/tinyxmlparser.cpp.i:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/TinyXML/tinyxmlparser.cpp.i
.PHONY : src/TinyXML/tinyxmlparser.cpp.i

src/TinyXML/tinyxmlparser.s: src/TinyXML/tinyxmlparser.cpp.s
.PHONY : src/TinyXML/tinyxmlparser.s

# target to generate assembly for a file
src/TinyXML/tinyxmlparser.cpp.s:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/TinyXML/tinyxmlparser.cpp.s
.PHONY : src/TinyXML/tinyxmlparser.cpp.s

src/cpp/Entitys.o: src/cpp/Entitys.cpp.o
.PHONY : src/cpp/Entitys.o

# target to build an object file
src/cpp/Entitys.cpp.o:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/Entitys.cpp.o
.PHONY : src/cpp/Entitys.cpp.o

src/cpp/Entitys.i: src/cpp/Entitys.cpp.i
.PHONY : src/cpp/Entitys.i

# target to preprocess a source file
src/cpp/Entitys.cpp.i:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/Entitys.cpp.i
.PHONY : src/cpp/Entitys.cpp.i

src/cpp/Entitys.s: src/cpp/Entitys.cpp.s
.PHONY : src/cpp/Entitys.s

# target to generate assembly for a file
src/cpp/Entitys.cpp.s:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/Entitys.cpp.s
.PHONY : src/cpp/Entitys.cpp.s

src/cpp/XmlParser.o: src/cpp/XmlParser.cpp.o
.PHONY : src/cpp/XmlParser.o

# target to build an object file
src/cpp/XmlParser.cpp.o:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/XmlParser.cpp.o
.PHONY : src/cpp/XmlParser.cpp.o

src/cpp/XmlParser.i: src/cpp/XmlParser.cpp.i
.PHONY : src/cpp/XmlParser.i

# target to preprocess a source file
src/cpp/XmlParser.cpp.i:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/XmlParser.cpp.i
.PHONY : src/cpp/XmlParser.cpp.i

src/cpp/XmlParser.s: src/cpp/XmlParser.cpp.s
.PHONY : src/cpp/XmlParser.s

# target to generate assembly for a file
src/cpp/XmlParser.cpp.s:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/XmlParser.cpp.s
.PHONY : src/cpp/XmlParser.cpp.s

src/cpp/controllers/Controller.o: src/cpp/controllers/Controller.cpp.o
.PHONY : src/cpp/controllers/Controller.o

# target to build an object file
src/cpp/controllers/Controller.cpp.o:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/controllers/Controller.cpp.o
.PHONY : src/cpp/controllers/Controller.cpp.o

src/cpp/controllers/Controller.i: src/cpp/controllers/Controller.cpp.i
.PHONY : src/cpp/controllers/Controller.i

# target to preprocess a source file
src/cpp/controllers/Controller.cpp.i:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/controllers/Controller.cpp.i
.PHONY : src/cpp/controllers/Controller.cpp.i

src/cpp/controllers/Controller.s: src/cpp/controllers/Controller.cpp.s
.PHONY : src/cpp/controllers/Controller.s

# target to generate assembly for a file
src/cpp/controllers/Controller.cpp.s:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/controllers/Controller.cpp.s
.PHONY : src/cpp/controllers/Controller.cpp.s

src/cpp/controllers/ControllerCollection.o: src/cpp/controllers/ControllerCollection.cpp.o
.PHONY : src/cpp/controllers/ControllerCollection.o

# target to build an object file
src/cpp/controllers/ControllerCollection.cpp.o:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/controllers/ControllerCollection.cpp.o
.PHONY : src/cpp/controllers/ControllerCollection.cpp.o

src/cpp/controllers/ControllerCollection.i: src/cpp/controllers/ControllerCollection.cpp.i
.PHONY : src/cpp/controllers/ControllerCollection.i

# target to preprocess a source file
src/cpp/controllers/ControllerCollection.cpp.i:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/controllers/ControllerCollection.cpp.i
.PHONY : src/cpp/controllers/ControllerCollection.cpp.i

src/cpp/controllers/ControllerCollection.s: src/cpp/controllers/ControllerCollection.cpp.s
.PHONY : src/cpp/controllers/ControllerCollection.s

# target to generate assembly for a file
src/cpp/controllers/ControllerCollection.cpp.s:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/controllers/ControllerCollection.cpp.s
.PHONY : src/cpp/controllers/ControllerCollection.cpp.s

src/cpp/controllers/PlayerController.o: src/cpp/controllers/PlayerController.cpp.o
.PHONY : src/cpp/controllers/PlayerController.o

# target to build an object file
src/cpp/controllers/PlayerController.cpp.o:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/controllers/PlayerController.cpp.o
.PHONY : src/cpp/controllers/PlayerController.cpp.o

src/cpp/controllers/PlayerController.i: src/cpp/controllers/PlayerController.cpp.i
.PHONY : src/cpp/controllers/PlayerController.i

# target to preprocess a source file
src/cpp/controllers/PlayerController.cpp.i:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/controllers/PlayerController.cpp.i
.PHONY : src/cpp/controllers/PlayerController.cpp.i

src/cpp/controllers/PlayerController.s: src/cpp/controllers/PlayerController.cpp.s
.PHONY : src/cpp/controllers/PlayerController.s

# target to generate assembly for a file
src/cpp/controllers/PlayerController.cpp.s:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/controllers/PlayerController.cpp.s
.PHONY : src/cpp/controllers/PlayerController.cpp.s

src/cpp/model/Game.o: src/cpp/model/Game.cpp.o
.PHONY : src/cpp/model/Game.o

# target to build an object file
src/cpp/model/Game.cpp.o:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/model/Game.cpp.o
.PHONY : src/cpp/model/Game.cpp.o

src/cpp/model/Game.i: src/cpp/model/Game.cpp.i
.PHONY : src/cpp/model/Game.i

# target to preprocess a source file
src/cpp/model/Game.cpp.i:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/model/Game.cpp.i
.PHONY : src/cpp/model/Game.cpp.i

src/cpp/model/Game.s: src/cpp/model/Game.cpp.s
.PHONY : src/cpp/model/Game.s

# target to generate assembly for a file
src/cpp/model/Game.cpp.s:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/model/Game.cpp.s
.PHONY : src/cpp/model/Game.cpp.s

src/cpp/model/StopWatch.o: src/cpp/model/StopWatch.cpp.o
.PHONY : src/cpp/model/StopWatch.o

# target to build an object file
src/cpp/model/StopWatch.cpp.o:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/model/StopWatch.cpp.o
.PHONY : src/cpp/model/StopWatch.cpp.o

src/cpp/model/StopWatch.i: src/cpp/model/StopWatch.cpp.i
.PHONY : src/cpp/model/StopWatch.i

# target to preprocess a source file
src/cpp/model/StopWatch.cpp.i:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/model/StopWatch.cpp.i
.PHONY : src/cpp/model/StopWatch.cpp.i

src/cpp/model/StopWatch.s: src/cpp/model/StopWatch.cpp.s
.PHONY : src/cpp/model/StopWatch.s

# target to generate assembly for a file
src/cpp/model/StopWatch.cpp.s:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/model/StopWatch.cpp.s
.PHONY : src/cpp/model/StopWatch.cpp.s

src/cpp/view/Screen.o: src/cpp/view/Screen.cpp.o
.PHONY : src/cpp/view/Screen.o

# target to build an object file
src/cpp/view/Screen.cpp.o:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/view/Screen.cpp.o
.PHONY : src/cpp/view/Screen.cpp.o

src/cpp/view/Screen.i: src/cpp/view/Screen.cpp.i
.PHONY : src/cpp/view/Screen.i

# target to preprocess a source file
src/cpp/view/Screen.cpp.i:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/view/Screen.cpp.i
.PHONY : src/cpp/view/Screen.cpp.i

src/cpp/view/Screen.s: src/cpp/view/Screen.cpp.s
.PHONY : src/cpp/view/Screen.s

# target to generate assembly for a file
src/cpp/view/Screen.cpp.s:
	$(MAKE) -f CMakeFiles/SiegeAlienEdition.dir/build.make CMakeFiles/SiegeAlienEdition.dir/src/cpp/view/Screen.cpp.s
.PHONY : src/cpp/view/Screen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... SiegeAlienEdition"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/SiegeAlienEdition.o"
	@echo "... src/SiegeAlienEdition.i"
	@echo "... src/SiegeAlienEdition.s"
	@echo "... src/TinyXML/tinystr.o"
	@echo "... src/TinyXML/tinystr.i"
	@echo "... src/TinyXML/tinystr.s"
	@echo "... src/TinyXML/tinyxml.o"
	@echo "... src/TinyXML/tinyxml.i"
	@echo "... src/TinyXML/tinyxml.s"
	@echo "... src/TinyXML/tinyxmlerror.o"
	@echo "... src/TinyXML/tinyxmlerror.i"
	@echo "... src/TinyXML/tinyxmlerror.s"
	@echo "... src/TinyXML/tinyxmlparser.o"
	@echo "... src/TinyXML/tinyxmlparser.i"
	@echo "... src/TinyXML/tinyxmlparser.s"
	@echo "... src/cpp/Entitys.o"
	@echo "... src/cpp/Entitys.i"
	@echo "... src/cpp/Entitys.s"
	@echo "... src/cpp/XmlParser.o"
	@echo "... src/cpp/XmlParser.i"
	@echo "... src/cpp/XmlParser.s"
	@echo "... src/cpp/controllers/Controller.o"
	@echo "... src/cpp/controllers/Controller.i"
	@echo "... src/cpp/controllers/Controller.s"
	@echo "... src/cpp/controllers/ControllerCollection.o"
	@echo "... src/cpp/controllers/ControllerCollection.i"
	@echo "... src/cpp/controllers/ControllerCollection.s"
	@echo "... src/cpp/controllers/PlayerController.o"
	@echo "... src/cpp/controllers/PlayerController.i"
	@echo "... src/cpp/controllers/PlayerController.s"
	@echo "... src/cpp/model/Game.o"
	@echo "... src/cpp/model/Game.i"
	@echo "... src/cpp/model/Game.s"
	@echo "... src/cpp/model/StopWatch.o"
	@echo "... src/cpp/model/StopWatch.i"
	@echo "... src/cpp/model/StopWatch.s"
	@echo "... src/cpp/view/Screen.o"
	@echo "... src/cpp/view/Screen.i"
	@echo "... src/cpp/view/Screen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

